### ISSUE TITLE
Add more array methods

### ISSUE THREAD

**Issue by mekolat** [themanaworld/tmwa#137]
- [ ] `sort` (asc, desc) **→ not possible because of #157**
- [ ] `shuffle` **→ not possible because of #157**
- [ ] `reverse` **→ not possible because of #157**
- [ ] `rotate` **→ not possible because of #157**
- [ ] `copy`
- [x] `search`
- [ ] `implode` or `join`

**Comment by mekolat** [comment]
issue #157 is a huge hindrance

**Comment by o11c** [comment]
Don't take the array size automatically, take it as an extra parameter. #157 is not a bug.

**Comment by mekolat** [comment]
oh good idea
