### ISSUE TITLE
PvP to-do list

### ISSUE THREAD

**Issue by mekolat** [themanaworld/tmwa#185]
- [ ] Reset the `@pvp` cooldown when attacking other players (maybe we could put this in `pc_iskiller`)
- [ ] Make use of real PvP ranking (right now it's just a kill streak)
- [ ] Get rid of `gangsterparadise`
- [ ] broadcast when the champion is dethroned
- [ ] reset the champion every month OR store in memory (= resets every release, on reboot)
