### ISSUE TITLE
Make scripts manage their own spell charges

### ISSUE THREAD

**Issue by mekolat** [themanaworld/tmwa#209]
- [ ] remove `charges` parameter from `overrideattack`
- [ ] never unset overridden weapons, give infinite charges until discharged by script
- [x] allow to call `overrideattack` without parameters (`overrideattack;`) to de-override (discharge)
  - [x] make a `#discharge` spell

OR

- [x] remove `charges` parameter from `overrideattack`
- [x] de-override after one use, make scripts override again after every use
